# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/imports/lab4/RAT-Microprocessor/ALU.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/imports/lab4/RAT-Microprocessor/ControlUnit.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/new/FlagReg.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/new/Flags.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/new/LOCATION.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/imports/lab4/RAT-Microprocessor/MCU.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/imports/new/PC.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/imports/new/PC_Mux.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/imports/lab4/RAT-Microprocessor/RegisterFile.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/new/SCR.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/new/SP.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/new/VGAdrive.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/imports/Assignment 1 Support Files/counter8b.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/imports/new/counter_for_one_shot.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/imports/new/debounce_one_shot_FSM.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/imports/lab4/prog_rom.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/new/ramVGA.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/new/vgaDriverBuffer.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/new/vga_clk_div.vhd}
  {C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/sources_1/new/RAT_Wrapper_W17.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/constrs_1/new/Constaints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Jesus Blanco/Documents/CPE233_FINAL_JAKEL_JESUSB/CPE233_FINAL_JAKEL_JESUSB.srcs/constrs_1/new/Constaints.xdc}}]


synth_design -top RAT_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RAT_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RAT_wrapper_utilization_synth.rpt -pb RAT_wrapper_utilization_synth.pb"
